language: cpp
sudo: required
dist: xenial
compiler:
  - gcc

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git submodule update --init -- "_site"
  - cd _site
  - git checkout gh-pages
  - cd ..
  - bundle install

script:
  - jekyll build --trace

after_success:
  - cd _site
  - git add --all
  - git commit -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER ."
  - git push --force --quiet https://$GH_TOKEN@github.com/tatsy/programming-for-beginners.git gh-pages:gh-pages

git:
  submodules: false

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
