# Setup
title:               cpp-python-beginners
tagline:             'Programming for everyone!'
description:         '初心者向けC++/Pythonプログラミング'
url:                 https://tatsy.github.io
baseurl:             '/cpp-python-beginners'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tatsuya Yatagawa
  url:               https://tatsy.github.io/
  email:             tatsy.mail@gmail.com

# GitHub
github:
  repo:              https://github.com/tatsy/cpp-python-beginners

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge