# Setup
title:               cpp-python-beginners
tagline:             'Programming for everyone!'
description:         '初心者向けC++/Pythonプログラミング'
url:                 https://tatsy.github.io
baseurl:             '/programming-for-beginners'
permalink:           pretty

# About/contact
author:
  name:              Tatsuya Yatagawa
  url:               https://tatsy.github.io/
  email:             tatsy.mail@gmail.com

# GitHub
github:
  repo:              https://github.com/tatsy/programming-for-beginners

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  python:
    output: true
    permalink: /:collection/:path/

  cpp:
    output: true
    permalink: /:collection/:path/